[programs.mainnet]
boom_token_minter = "AHKxToTXajkn9gt2Y2WpAuRVMFT8sYnw362Bm9Too4Qw"

[provider]
cluster = "https://necessary-warmhearted-water.solana-mainnet.quiknode.pro/f6dc40df50b9889088298d791735269589007907''

[scripts]
test = "mocha"
